AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'tmp/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
  DisplayCopNames: true

Rails:
  Enabled: true

Documentation:
  Enabled: false

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

MethodLength:
  CountComments: false
  Max: 40

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/LineLength:
  Enabled: false
