MibParseKey = {
  '1.3.6.1.2.1.2.2.1.6.1' => ['Mac_Address'],
  '1.3.6.1.2.1.1.6.0' => ['Location'],
  '1.3.6.1.2.1.1.4.0' => ['Contact'],
  '1.3.6.1.4.1.2435.2.3.9.4.2.1.5.5.10.0' => ['Total_Page_Count', 'Monochrome_Page_Count', 'Color_Page_Count'],
  '1.3.6.1.4.1.2435.2.3.9.4.2.1.5.5.8.0' => ['TonerInk_Black', 'TonerInk_Cyan', 'TonerInk_Magenta', 'TonerInk_Yellow',
                                             'Drum_Unit', 'Drum_Unit_Black', 'Drum_Unit_Cyan', 'Drum_Unit_Magenta',
                                             'Drum_Unit_Yellow', 'PFKit1_Status', 'PFKit2_Status', 'PFKit3_Status',
                                             'PFKit4_Status', 'PFKit5_Status', 'PFKitMP_Status', 'FuserUnit_Status',
                                             'LaserUnit_Status', 'Belt_Unit', 'Waste_TonerPack', 'TonerInk_LifeBlack',
                                             'TonerInk_LifeCyan', 'TonerInk_LifeMagenta', 'TonerInk_LifeYellow',
                                             'Drum_Count', 'Drum_Count_Black', 'Drum_Count_Cyan', 'Drum_Count_Magenta',
                                             'Drum_Count_Yellow'
                                           ],
  '1.3.6.1.4.1.2435.2.3.9.4.2.1.5.5.11.0' => ['Drum_Unit_Remaining_Life', 'Drum_Unit_Black_Remaining_Life',
                                              'Drum_Unit_Cyan_Remaining_Life', 'Drum_Unit_Magenta_Remaining_Life',
                                              'Drum_Unit_Yellow_Remaining_Life', 'Paper_Feeding_Kit_1_Remaining_Life',
                                              'Paper_Feeding_Kit_2_Remaining_Life', 'Paper_Feeding_Kit_3_Remaining_Life',
                                              'Paper_Feeding_Kit_4_Remaining_Life', 'Paper_Feeding_Kit_5_Remaining_Life',
                                              'Paper_Feeding_Kit_MP_Remaining_Life', 'Fuser_Unit_Remaining_Life',
                                              'Laser_Unit_Remaining_Life', 'Belt_Unit_Remaining_Life'
                                            ],
  '1.3.6.1.4.1.2435.2.3.9.4.2.1.5.5.20.0' => ['TonerInk_Black_Replace_Count', 'TonerInk_Cyan_Replace_Count',
                                              'TonerInk_Magenta_Replace_Count', 'TonerInk_Yellow_Replace_Count',
                                              'Drum_Unit_Replace_Count', 'Drum_Unit_Black_Replace_Count',
                                              'Drum_Unit_Cyan_Replace_Count', 'Drum_Unit_Magenta_Replace_Count',
                                              'Drum_Unit_Yellow_Replace_Count', 'Paper_Feeding_Kit_1_Replace_Count',
                                              'Paper_Feeding_Kit_2_Replace_Count', 'Paper_Feeding_Kit_3_Replace_Count',
                                              'Paper_Feeding_Kit_4_Replace_Count', 'Paper_Feeding_Kit_5_Replace_Count',
                                              'Paper_Feeding_Kit_MP_Replace_Count', 'Fuser_Unit_Replace_Count',
                                              'Laser_Unit_Replace_Count', 'Belt_Unit_Replace_Count',
                                              'Waste_Toner_Box_Replace_Count'
                                            ],
  '1.3.6.1.4.1.2435.2.3.9.4.2.1.5.5.52.2.1.2' => ['Print_Page_SxDx_Count_A4Letter', 'Print_Mono_Page_SxDx_Count_A4Letter',
                                                  'Print_Color_Page_SxDx_Count_A4Letter', 'Print_Page_SxDx_Count_A5B5',
                                                  'Print_Mono_Page_SxDx_Count_A5B5', 'Print_Color_Page_SxDx_Count_A5B5',
                                                  'Print_Page_SxDx_Count_LegalB4', 'Print_Mono_Page_SxDx_Count_LegalB4',
                                                  'Print_Color_Page_SxDx_Count_LegalB4', 'Print_Page_SxDx_Count_A3Ledger',
                                                  'Print_Mono_Page_SxDx_Count_A3Ledger', 'Print_Color_Page_SxDx_Count_A3Ledger',
                                                  'Print_Page_SxDx_Count_4x6Postcard', 'Print_Mono_Page_SxDx_Count_4x6Postcard',
                                                  'Print_Color_Page_SxDx_Count_4x6Postcard', 'Print_Page_SxDx_Count_Other',
                                                  'Print_Mono_Page_SxDx_Count_Other', 'Print_Color_Page_SxDx_Count_Other',
                                                ],
  '1.3.6.1.4.1.2435.2.3.9.4.2.1.5.5.18.0' => ['Black_Coverage', 'Cyan_Coverage', 'Magenta_Coverage', 'Yellow_Coverage'],
  '1.3.6.1.4.1.2435.2.3.9.4.2.1.5.5.6.0' => ['USTATUS']
}
