require 'bundler/gem_tasks'
require 'rake/testtask'
require 'rubocop/rake_task'

RuboCop::RakeTask.new

Rake::Task[:release].clear
desc "Create tag and build."
task :release => [:coverage, :rubocop, :build, 'release:guard_clean', 'release:source_control_push'] do
end

task :coverage do
  ENV['COVERAGE'] = 'true'
  Rake::Task[:test].invoke
end

Rake::TestTask.new do |t|
  t.libs << 'test'
  t.pattern = "test/**/test_*.rb"
end
